version: 2

sources:
  - name: raw
    schema: raw_today
    tables:
      - name: orders
        columns:
          - name: order_id
            data_tests:
              - unique
              - not_null
      - name: order_items
      - name: products
      - name: users

models:
  - name: stg_order
    columns:
      - name: order_id
        data_tests:
          - unique
          - not_null
